version: 2

project_name: tf-why

builds:
  - main: ./cmd/tf-why
    binary: tf-why
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X main.version={{.Version}}
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"

release:
  github:
    owner: djeeteg007
    name: tf-why

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
